project:
  type: website

website:
  title: "Marco-Iglesias-Nottingham.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  revealjs:
    css: styles.css
    toc: true



